# Generated by Django 4.1.5 on 2023-01-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apartment_number_alter_company_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='gate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.gate'),
        ),
    ]
