# Generated by Django 4.1.5 on 2023-01-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_apartment_gate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
